import Image from "next/image";
import Link from "next/link";
import InterestForm from "../components/InterestForm";
import { getEvents } from "../lib/content";

export default async function HomePage() {
  const events = await getEvents();
  return <main>
    <a href="#events" className="absolute left-4 top-3 z-20 -translate-y-20 rounded-md bg-white px-4 py-2 font-bold text-slate-900 transition focus:translate-y-0">Skip to events</a>
    <section className="bg-teal-950 px-6 pb-20 pt-6 text-white sm:px-10 lg:px-16">
      <div className="mx-auto max-w-6xl"><nav aria-label="Main navigation" className="flex items-center justify-between"><Link href="#top" className="text-xl font-bold tracking-tight">common<span className="text-amber-300">ground</span>.</Link><div className="hidden gap-7 text-sm text-teal-100 md:flex"><Link href="#events" className="hover:text-white">Events</Link><Link href="#about" className="hover:text-white">About</Link></div><Link href="#updates" className="rounded-full border border-white/25 px-4 py-2 text-sm font-bold transition hover:bg-white hover:text-teal-950">Get updates</Link></nav>
        <div id="top" className="grid gap-10 pb-4 pt-20 lg:grid-cols-[1.08fr_.92fr] lg:items-center lg:pt-28"><div><p className="rise text-sm font-bold uppercase tracking-[0.2em] text-amber-300">Local ideas, shared energy</p><h1 className="rise rise-delay mt-5 max-w-3xl text-5xl font-bold leading-[.98] tracking-tight sm:text-6xl lg:text-7xl">Make room for the people and ideas around you.</h1><p className="rise rise-delay mt-7 max-w-xl text-lg leading-8 text-teal-100">Common Ground hosts practical talks and workshops for curious people who want to shape more thoughtful communities.</p><Link href="#events" className="rise rise-delay mt-9 inline-block rounded-full bg-amber-300 px-6 py-3 font-bold text-slate-900 transition hover:bg-amber-200">See upcoming events</Link></div><Image src="/frontend-development-internship-portfolio/week07-community-events/out/community-scene.svg" alt="Illustration of people gathering around a shared table" width={720} height={560} priority sizes="(max-width: 1024px) 100vw, 45vw" className="rise w-full rounded-[2rem] border border-white/10 bg-teal-900 shadow-2xl" /></div>
      </div>
    </section>
    <section id="events" aria-labelledby="events-heading" className="px-6 py-20 sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-teal-700">Coming up</p><h2 id="events-heading" className="mt-3 text-4xl font-bold tracking-tight sm:text-5xl">Join the conversation.</h2></div><p className="max-w-sm leading-7 text-slate-600">Small groups, honest questions and useful ideas to take home.</p></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{events.map((event) => <article key={event.title} className="rounded-3xl bg-white p-6 shadow-lift ring-1 ring-slate-200"><div className="flex items-start justify-between"><p className="text-sm font-bold text-teal-700">{event.type}</p><p className="rounded-2xl bg-amber-100 px-3 py-2 text-center text-xs font-bold text-slate-700"><span className="block">{event.month}</span><span className="mt-1 block text-xl leading-none text-slate-950">{event.day}</span></p></div><h3 className="mt-9 text-2xl font-bold leading-tight">{event.title}</h3><p className="mt-4 leading-7 text-slate-600">{event.description}</p><dl className="mt-7 space-y-2 border-t border-slate-100 pt-4 text-sm"><div className="flex justify-between gap-3"><dt className="text-slate-500">Time</dt><dd className="font-semibold">{event.time}</dd></div><div className="flex justify-between gap-3"><dt className="text-slate-500">Place</dt><dd className="text-right font-semibold">{event.place}</dd></div></dl></article>)}</div></div></section>
    <section id="about" className="bg-amber-100 px-6 py-20 sm:px-10 lg:px-16"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-3"><div><p className="text-sm font-bold uppercase tracking-[0.2em] text-teal-700">How it works</p><h2 className="mt-3 text-4xl font-bold tracking-tight">Friendly by design.</h2></div><p className="rounded-3xl bg-white p-6 leading-7 shadow-lift">Every event is designed to be easy to join. Clear timings, step-free spaces and an open invitation to participate in your own way.</p><p className="rounded-3xl bg-white p-6 leading-7 shadow-lift">The event details live in a separate content layer, allowing a team to update dates and descriptions without rebuilding the interface.</p></div></section>
    <section id="updates" className="bg-teal-950 px-6 py-20 text-white sm:px-10 lg:px-16"><div className="mx-auto max-w-6xl rounded-[2rem] border border-white/10 bg-teal-900 p-8 shadow-2xl sm:p-12"><p className="text-sm font-bold uppercase tracking-[0.2em] text-amber-300">Stay in the loop</p><h2 className="mt-4 max-w-xl text-4xl font-bold tracking-tight">A few good reasons to get together.</h2><p className="mt-4 max-w-xl leading-7 text-teal-100">New event dates and workshop details, sent occasionally.</p><InterestForm /></div></section>
  </main>;
}
